### ISSUE TITLE
Add `rtraverse` and `ltraverse` 

### ISSUE THREAD

**Issue by sigma-andex** [jacob-alford/bifold-traverse#2]
See e.g. https://pursuit.purescript.org/packages/purescript-foldable-traversable/6.0.0/docs/Data.Bitraversable#v:ltraverse

**Comment by rae-hill** [comment]
These were added in version 1.1.0, see these release notes:

https://github.com/jacob-alford/bifold-traverse/releases/tag/1.1.0

**Comment by rae-hill** [comment]
Note: I did not add traverseRight to some instances, namely either and these because those are the same as traverse from fp-ts
